### ISSUE TITLE
Button for copying the link to a page.

### ISSUE THREAD

**Issue by larryyueli** [larryyueli/slidechat#66]
Right now, we have a button that we can use to easily copy the link to a question. It would be good to have a similar button for copying the link to a page of the slides because people want to refer to a page instead of a question.

**Comment by lvlingxiao1** [comment]
I think they can just copy the link from the browser. Do we really need a button?

**Comment by lvlingxiao1** [comment]
(Ok, maybe a button can create the markdown for the link, ignore my question)

**Comment by lvlingxiao1** [comment]
@larryyueli  do you have any ideas where you want to put that button? This is the only challenge of this feature

**Comment by larryyueli** [comment]
How about this?
![image](https://user-images.githubusercontent.com/3384353/106848175-6e74e880-667e-11eb-850d-28770a6831d9.png)

**Comment by lvlingxiao1** [comment]
I'd say placing it there doesn't make users know what it does immediately... but I can't think of a better place XD

**Comment by larryyueli** [comment]
Make sure to explain it with the alt text when the user hovers over the icon :)

**Comment by lvlingxiao1** [comment]
ok, that's no problem
