### ISSUE TITLE
Sharing presentation link broken?

### ISSUE THREAD

**Issue by amjadhassoun123123** [larryyueli/slidechat#93]
When sharing a presentation link (via the share link button), for example the demo slides , we get the output:

[@SlideChat.pdf/Page 1](https://mcsapps.utm.utoronto.ca/slidechat/5f1b35eb3997b943b856e362/1)
Is this supposed to happen? When I paste this in the browser, it obviously doesn't work.

**Comment by lvlingxiao1** [comment]
Hi, as you might already noticed, it got converted into a link in GitHub issue. The copied text
```
[@SlideChat.pdf/Page 1](https://mcsapps.utm.utoronto.ca/slidechat/5f1b35eb3997b943b856e362/1)
```
is in Markdown syntax, where the first part is displayed text and the second part is the link. You can paste that into SlideChat reply box of question body, it will be converted as well

**Comment by amjadhassoun123123** [comment]
Ok I see, but when you copy that link directly into the browser it won't work. Is that what you guys are going for? To let the user see that the second part is the link and delete the rest on his own?

**Comment by lvlingxiao1** [comment]
I see your point. We thought this feature might be mostly used in linking to another question/page in the chat, so we made it that way. If you want to just copy the link, you can copy the browser URL :)

**Comment by amjadhassoun123123** [comment]
Ok sounds good, just wanted to point it out.

Thanks @lvlingxiao1 .
